### ISSUE TITLE
Console getting spammed with error banfromclaim 1.5.5

### ISSUE THREAD

**Issue by CrispyDairy** [Baktus79/BanFromClaim#10]
**Describe the bug**
This started happening out of nowhere, I'm using latest builds of both banfrom claim, and griefdefender

---

**ERROR MESSAGE**
```
## [12:10:20 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.5
java.lang.LinkageError: loader constraint violation: when resolving interface method 'com.griefdefender.api.claim.Claim com.griefdefender.api.claim.ClaimManager.getClaimAt(com.flowpowered.math.vector.Vector3i)' the class loader org.bukkit.plugin.java.PluginClassLoader @10866457 of the current class, no/vestlandetmc/BanFromClaim/listener/GDListener, and the class loader org.bukkit.plugin.java.PluginClassLoader @15a66146 for the method's defining class, com/griefdefender/api/claim/ClaimManager, have different Class objects for the type com/flowpowered/math/vector/Vector3i used in the signature (no.vestlandetmc.BanFromClaim.listener.GDListener is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @10866457, parent loader 'app'; com.griefdefender.api.claim.ClaimManager is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @15a66146, parent loader 'app')
        at no.vestlandetmc.BanFromClaim.listener.GDListener.onPlayerEnterClaim(GDListener.java:39) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor808.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1163]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Purpur-1163]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1163]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1527) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1308) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1152) ~[patched_1.16.5.jar:git-Purpur-1163]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1163]
        at java.lang.Thread.run(Unknown Source) [?:?]##
```

---

**Additional server information**
Purpur 1.16.5
**BanFromClaim version:*1.5.5*
**Server version (use /ver):*Purpur 1.16.5*
**Plugin list:Plugins (81): ajLeaderboards, AutoMessager, BanFromClaim, BetterSleeping3, BlueMap, BotSentry*, Brewery, BuycraftX, ChatControlRed, Citizens, CitizensText, ClickSortLite, CommandAlias, CommandDefender, CoreProtect, CustomEnderChest, DiscordBotAPI*, DiscordSRV, DiscordSRV-Staff-Chat, Essentials, EssentialsProtect, EssentialsSpawn, EvenMoreFish, FarmLimiter, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, GriefDefender, GSit, Hat, HolographicDisplays, HolographicExtension, ImageOnMap, InventoryRollback, InvisibleItemFrames, InvSeePlusPlus, LagAssist, LiteBans, LuckPerms, MarriageMaster, MineAlert, MoneyNote*, Multiverse-Core, NexelWilderness, OpenAudioMc, Parties, PetTeleport, PhatLoots, PlaceholderAPI, Plan, PlayerParticles, PlayerWarps, PlayTime*, PlugMan, PremiumVanish, ProtocolLib, PvPManager, pvpstats*, Quests, QuestsGUI, Referral, Sentinel, Shopkeepers, SimpleRename, Skript, SlotMachine, SmoothTimber, StaffPlus, TAB, Tamablefoxes, TrollingFreedom, UltimateAutoRestart, Vault, VeinMiner, ViaBackwards, ViaVersion, Votifier, VotingPlugin, Vouchers, Vulcan, WorldGuard, WorldGuardExtraFlags**

**Comment by Baktus79** [comment]
#9

**Comment by CrispyDairy** [comment]
Ah I see, well there is my plugins list if that helps

**Comment by Baktus79** [comment]
Yes, very good. There must be a conflict with a plugin. GriefDefender 2.0 will remove this issue as it will no longer  use the conflicted library
