### ISSUE TITLE
[Bug] Task #637 for BanFromClaim v1.5.6 generated an exception

### ISSUE THREAD

**Issue by CrispyDairy** [Baktus79/BanFromClaim#12]
**Describe the bug**
Not sure, just showed up in console.

---

**ERROR MESSAGE**
```
[02:32:03 WARN]: [BanFromClaim] Task #637 for BanFromClaim v1.5.6 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1584) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1607) ~[?:?]
        at no.vestlandetmc.BanFromClaim.handler.CombatScheduler.run(CombatScheduler.java:18) ~[BanFromClaim-1.5.6.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Purpur-1371]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Purpur-1371]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1574) ~[patched_1.17.1.jar:git-Purpur-1371]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1371]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Purpur-1371]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1283) ~[patched_1.17.1.jar:git-Purpur-1371]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1371]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

---

**Additional server information**

**BanFromClaim version: BanFromClaim version 1.5.6**
**Server version (use /ver): This server is running Purpur version git-Purpur-1371 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 8c2e417 on ver/1.17.1)**
**Plugin list: Plugins (79): AdvancedEnchantments, ajLeaderboards, BanFromClaim, Battleship*, BlueMap, Brewery, BuycraftX, ChatControlRed, Citizens, ClickSortLite, CMILib, CommandAlias, CommandDefender, CoreProtect, CustomCrafting, DangerousCaves, DeluxeMenus, DiscordBotAPI*, DiscordSRV, DoorsReloaded, EnderContainers, Essentials, EssentialsSpawn, EvenMoreFish, FarmLimiter, FastAsyncWorldEdit (WorldEdit), FastChunkPregenerator, FearFeeling, GriefDefender, GSit, HoloExtension, HolographicDisplays, HolographicExtension, ImageMaps, InventoryRollbackPlus, InvSeePlusPlus, Jobs, LagAssist, LevelledMobs, LiteBans, LuckPerms, LumberJack, MarriageMaster, MineAlerts, MiniaturePets, MiniMOTD, MoneyNote, MoreMobHeads, Multiverse-Core, Multiverse-Portals, NashornPlus, OpenAudioMc, PartyChat, PlaceholderAPI, Plan, PlayerParticles, PlayerWarps, PremiumVanish, ProtocolLib, PvPManager, pvpstats, Randomtp, Sentinel, Shopkeepers, SlotMachine, SpiritFood, TAB, TabCompleteFilter, Tamablefoxes, UltimateAutoRestart, Vault, VeinMiner, Votifier, VotingPlugin, Vouchers, Vulcan, WolfyUtilities, WorldGuard, WorldGuardExtraFlags**

**Comment by Baktus79** [comment]
This should now be fixed. Thank you for your feedback!
