### ISSUE TITLE
Add a command that prohibits everyone from entering my land

### ISSUE THREAD

**Issue by thiagogebrimm** [Baktus79/BanFromClaim#13]
The command could be like this: I give "/banfcall" and it would ban everyone from entering my land, however if the player has trust or any permission the ban would not affect him.

**Comment by Baktus79** [comment]
This is in the works, and will be released in a couple of days.

**Comment by Baktus79** [comment]
Ban all players feature has now been committed and will be released in a very short time.
[[22b9c24e2ec58cf0f1b3d8aae0aaedf6fc13d704](https://github.com/Baktus79/BanFromClaim/commit/22b9c24e2ec58cf0f1b3d8aae0aaedf6fc13d704)]

**Comment by thiagogebrimm** [comment]
Error in the new version:
```
[13:07:42 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.file.FileConfiguration.contains(String)" because "this.cfg" is null
        at no.vestlandetmc.BanFromClaim.config.ClaimData.isAllBanned(ClaimData.java:72) ~[BanFromClaim-1.5.8.jar:?]
        at no.vestlandetmc.BanFromClaim.listener.GPListener.onPlayerEnterClaim(GPListener.java:48) ~[BanFromClaim-1.5.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1206.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1378]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1378]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1378]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1522) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(PacketPlayInFlying.java:114) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPosition.a(PacketPlayInFlying.java:42) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1433) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1411) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1382) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1293) ~[patched_1.17.1.jar:git-Purpur-1378]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1378]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Baktus79** [comment]
I have fixed this in 1.5.9. I rushed to get the feature done, and forgot to check for GriefPrevention.

**Comment by thiagogebrimm** [comment]
They are still managing to enter the players' territory even with "/bfcall"

**Comment by Baktus79** [comment]
I'll check.

**Comment by Baktus79** [comment]
Now its fixed!

**Comment by thiagogebrimm** [comment]
It would be nice if the player has /accesstrust it would be enough to get around the ban, is as a suggestion for an upcoming update. :)

**Comment by Baktus79** [comment]
Sure, I'll keep that in mind. Per now its only build and permissiontrust that has access, but Im open to the others aswell.
