### ISSUE TITLE
[Bug] IllegalArgumentException UUID cannot be null

### ISSUE THREAD

**Issue by zikehalil3535** [Baktus79/BanFromClaim#16]
**Describe the bug**

---

**ERROR MESSAGE**
```
[20:26:17] [Server thread/WARN]: [BanFromClaim] Task #206 for BanFromClaim v1.5.11 generated an exception
java.lang.IllegalArgumentException: UUID cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.17.1.jar:git-Airplane-112]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.getOfflinePlayer(CraftServer.java:1843) ~[patched_1.17.1.jar:git-Airplane-112]
	at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1130) ~[patched_1.17.1.jar:git-Airplane-112]
	at no.vestlandetmc.BanFromClaim.handler.CombatScheduler.run(CombatScheduler.java:25) ~[BanFromClaim-1.5.11.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Airplane-112]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Airplane-112]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Airplane-112]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:492) ~[patched_1.17.1.jar:git-Airplane-112]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Airplane-112]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Airplane-112]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Airplane-112]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

---

**Additional server information**

**BanFromClaim version:** Latest
**Server version (use /ver):** 1.17.1
**Plugin list:**

**Comment by Baktus79** [comment]
I need more information regarding this. In what situation does this happen?

**Comment by zikehalil3535** [comment]
> I need more information regarding this. In what situation does this happen?

If new players joining server giving this error

**Comment by Baktus79** [comment]
Are your server in offline mode?

**Comment by zikehalil3535** [comment]
Yeah Im using offline mode

**Comment by Baktus79** [comment]
Yes, then I understand that it will not work. Offline servers do not use UUID on the players. BFC uses UUID to store players.

**Comment by zikehalil3535** [comment]
Then what can I do still giving warn and error
![image](https://user-images.githubusercontent.com/88826436/151670698-cd94b0e0-6240-429c-931b-2458c5f00890.png)

**Comment by Baktus79** [comment]
There's nothing I can do about it as long as it's made for online servers. The error that occurs is because offline servers do not have real UUIDs.
