### ISSUE TITLE
[Bug] Erro in kickfromclaim 

### ISSUE THREAD

**Issue by thiagogebrimm** [Baktus79/BanFromClaim#19]
**Describe the bug**
When using the command the player is not kicked out and a warn appears on the console, i use GriefPrevention

---

**ERROR MESSAGE**
```
[16:08:18 INFO]: thiagogebrim issued server command: /kickfromclaim ManuUrsinha
[16:08:18 WARN]: [BanFromClaim] Plugin BanFromClaim v1.6.0 generated an exception while executing task 23955168
java.lang.NoClassDefFoundError: com/griefdefender/api/GriefDefender
        at no.vestlandetmc.BanFromClaim.handler.LocationFinder.IterateCircumferencesGD(LocationFinder.java:33) ~[BanFromClaim-1.6.0.jar:?]
        at no.vestlandetmc.BanFromClaim.commands.griefprevention.KfcCommandGP.lambda$onCommand$1(KfcCommandGP.java:79) ~[BanFromClaim-1.6.0.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1581]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1581]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1581]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.griefdefender.api.GriefDefender
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 8 more
```

---

**Additional server information**

**BanFromClaim version:*1.6.0*
**Server version (use /ver):*git-Purpur-1581 (MC: 1.18.2)**
**Plugin list:**

**Comment by Baktus79** [comment]
This is fixed in version 1.6.1. Thanks for your feedback!
