### ISSUE TITLE
Null UUID when combat mode is active

### ISSUE THREAD

**Issue by dominik235** [Baktus79/BanFromClaim#23]
**Describe the bug**
When claim owner stands in his claim and hits a player that is banned and is outside of his claim I get this exception

---

**ERROR MESSAGE**
```
[00:01:19] [Server thread/WARN]: [BanFromClaim] Task #7 for BanFromClaim v1.6.2 generated an exception
java.lang.IllegalArgumentException: UUID cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[commons-lang-2.6.jar:2.6]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.getOfflinePlayer(CraftServer.java:1833) ~[paper-1.19.jar:git-Paper-28]
	at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:1255) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
	at no.vestlandetmc.BanFromClaim.handler.CombatScheduler.run(CombatScheduler.java:25) ~[BanFromClaim-1.6.2.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-28]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-28]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[paper-1.19.jar:git-Paper-28]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-28]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-28]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-28]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-28]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

---

**Additional server information**

**BanFromClaim version: 1.6.2**
**Server version (use /ver): git-Paper-28 1.19**
**Plugin list: BanFromClaim, GriefPrevention(16.18)**

**Comment by Baktus79** [comment]
I will take a look at this

**Comment by Baktus79** [comment]
This should be fixed with the next release.
