### ISSUE TITLE
[Bug]PlayerMoveEvent

### ISSUE THREAD

**Issue by xaprier** [Baktus79/BanFromClaim#24]
**Server Version** : Paper 1.15.2
**Java Version** : AdoptOpenJDK 14
When a player is banned from claim and he can enter the claim. Console gives that error:
```
[10:55:56] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.6.2
java.lang.NoSuchMethodError: 'java.util.UUID me.ryanhamshire.GriefPrevention.Claim.getOwnerID()'
	at no.vestlandetmc.BanFromClaim.listener.GPListener.hasTrust(GPListener.java:123) ~[?:?]
	at no.vestlandetmc.BanFromClaim.listener.GPListener.onPlayerEnterClaim(GPListener.java:48) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor735.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-393]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-393]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-393]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1153) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1233) ~[patched_1.15.2.jar:git-Paper-393]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-393]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by Baktus79** [comment]
It says right here that the GriefPrevention method for ownerID does not exist.
`java.lang.NoSuchMethodError: 'java.util.UUID me.ryanhamshire.GriefPrevention.Claim.getOwnerID()'`

Are you using the latest GreifPrevention version 16.18?

**Comment by xaprier** [comment]
I checked it out. My server is running 1.15.2 version of Minecraft, and latest version of GriefPrevenntion not supported it. So i use version 16.13.0 for that. What BFC version should i use for that version of GriefPrevention?

**Comment by Baktus79** [comment]
I'm sorry, but the earliest version I've compiled against is 16.17.

**Comment by xaprier** [comment]
I have the 1.5.6 version of BFC in my backup files. Is it supporting?

**Comment by Baktus79** [comment]
I am sorry, but I have not testet with older than 16.17. There might be API changes between those versions and therefor it might not work.

**Comment by xaprier** [comment]
Thank you, i will figure out this situation
