### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by BookWyrm114** [Baktus79/BanFromClaim#4]
**Describe the bug**

---

**ERROR MESSAGE**
![image](https://user-images.githubusercontent.com/79489385/114893973-360b2c80-9ddc-11eb-8286-c6aefbbb66f5.png)
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:05 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:06 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:06 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:06 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:06 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:06 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:06 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:06 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:06 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:07 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
[11:14:08 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null

whenever a user is moving outside of a claimed area, this error is constantly reported for every single movement made by the player
---

**Additional server information**

**BanFromClaim version: 1.5.2**
**Server version (use /ver): git-Paper-592**
**Plugin list: AcuteLoot, Admin-GUI, AdvancedBan, AdvancedBanAutoBan, AdvancedEnchantments, AlchemicalArrows, AnvilOverride, ArmoredElytra, BKCommonLib, BanFromClaim, BetterBeacons, BetterCommandSpy, BetterInvisibility, BlueMap, BossShopPro, ChestShop, ColoredAnvils, ConsoleSpamFix, CoreProtect, CoreProtectTNT, Dimensions, DisableReload, DropHeads, EnergeticStorage, Essentials, EssentialsSpawn, FakePlayers, FastAsyncWorldEdit, Graves, GriefPrevention, GriefPreventionFlags, HolographicDisplays, HolographicExtension, HorseTpWithMe, Illusioner, InteractionVisualizer, InventoryRollbackPlus, ItemBridge, LavaSponge, LibsDisguises, LightAPI, LittleThings, LockSecurity, LoneLibs, Lootin, LuckPerms, MCGBluemapEssentials, MobMoneyX, MoneyNote, Multiverse-Core, Multiverse-Inventories, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, NBTAPI, Nations, OfflineEditor, OfflineGrowth, OpenAudioMc, OpenInv, PlaceholderAPI, PlayerAuctions, PluginConstructorAPI, ProtectionLib, ProtocolLib, PunishGUI, React, RecipeControl, ServerBooster, ServerUtils, SilkSpawners, SimpleRename, Sudo, SuperVanish, TileDataSaver, TitleManager, TradeUI, TrollingFreedom, UberEnchant, VanillaTweaks, Vault, ViaVersion, VoidGenerator, Vouchers, WitherXP and WuufusWaygates**

**Comment by BookWyrm114** [comment]
I tried restarting the server, but now the error message is the same, but now it's even longer.
[12:16:52 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
	at no.vestlandetmc.BanFromClaim.listener.GPListener.onPlayerEnterClaim(GPListener.java:31) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor846.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-592]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1409) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-592]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[12:16:52 ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.5.2
java.lang.NullPointerException: null
	at no.vestlandetmc.BanFromClaim.listener.GPListener.onPlayerEnterClaim(GPListener.java:31) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor846.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-592]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-592]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1409) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1319) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-592]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-592]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Baktus79** [comment]
Thank you for your feedback! This bug was a sluggishness on my part. Releases a new update now.

**Comment by BookWyrm114** [comment]
Thank you!
