### ISSUE TITLE
[Bug] Could not pass event PlayerMoveEvent to BanFromClaim v1.7.0

### ISSUE THREAD

**Issue by MrRockis** [Baktus79/BanFromClaim#44]
**Describe the bug**
We are getting random errors from BanFromClaim when using it on 1.21.

---

**ERROR MESSAGE**
```
## [17:10:40] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to BanFromClaim v1.7.0
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because the return value of "me.ryanhamshire.GriefPrevention.Claim.checkPermission(java.util.UUID, me.ryanhamshire.GriefPrevention.ClaimPermission, org.bukkit.event.Event)" is null
	at BanFromClaim.jar/no.vestlandetmc.BanFromClaim.hooks.GriefPreventionHook.hasTrust(GriefPreventionHook.java:88) ~[BanFromClaim.jar:?]
	at BanFromClaim.jar/no.vestlandetmc.BanFromClaim.listener.RegionListener.onPlayerEnterClaim(RegionListener.java:56) ~[BanFromClaim.jar:?] ##
```

---

**Additional server information**

**BanFromClaim version:** 1.7.0
**Server version (use /ver):** Paper 1.21 build #44
**Plugin list:** N/A

**Comment by Baktus79** [comment]
New release has it fixed.
