### ISSUE TITLE
[Bug] NoSuchMethodError: 'me.ryanhamshire.GriefPrevention.Claim.getOwnerID()'

### ISSUE THREAD

**Issue by Leyiraa** [Baktus79/BanFromClaim#49]
**Describe the bug**

---

**ERROR MESSAGE**
```
## - [Sun 02:35:52 ERROR Minecraft] Could not pass event PlayerMoveEvent to BanFromClaim v1.7.4
java.lang.NoSuchMethodError: 'java.util.UUID me.ryanhamshire.GriefPrevention.Claim.getOwnerID()'
    at no.vestlandetmc.BanFromClaim.hooks.GriefPreventionHook.getOwnerID(GriefPreventionHook.java:73)
    at no.vestlandetmc.BanFromClaim.listener.RegionListener.onPlayerEnterClaim(RegionListener.java:41)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor707.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
    at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1527)
    at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122)
    at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18)
    at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
    at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
    at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
    at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
    at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
    at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1339)
    at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1332)
    at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95)
    at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1469)
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1142)
    at net.minecraft.server.v1_16_R3.Minecra##
```

---

**Additional server information**

**BanFromClaim version:**   v1.7.4
**Server version (use /ver):** 1.16.5
**Plugin list:**
![image](https://github.com/user-attachments/assets/34b7c9db-fbee-44f7-9869-07ec3bf0fd55)

**Comment by Baktus79** [comment]
Are you using the latest GriefPrevention?

**Comment by Baktus79** [comment]
Cannot reproduce. The error message `NoSuchMethodError` is saying that the method doesnt exist. If GriefPrevention is loaded it should not be any problems.
