### ISSUE TITLE
[Bug] NullPointerException getOwnerID()

### ISSUE THREAD

**Issue by KinczeK** [Baktus79/BanFromClaim#53]
**Describe the bug**
There's a NullPointerException spamming server's console.

---

**ERROR MESSAGE**
```
Could not pass event PlayerMoveEvent to BanFromClaim v1.7.4
java.lang.NullPointerException: Cannot invoke "me.ryanhamshire.GriefPrevention.Claim.getOwnerID()" because "claim" is null
        at no.vestlandetmc.BanFromClaim.hooks.GriefPreventionHook.getOwnerID(GriefPreventionHook.java:73) ~[Banfromclaim.jar:?]
        at no.vestlandetmc.BanFromClaim.listener.RegionListener.onPlayerEnterClaim(RegionListener.java:41) ~[Banfromclaim.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor2109.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfishplus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfishplus-api-1.20.4-R0.1-SNAPSHOT.jar:git-PufferfishPlus-46]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfishplus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent() ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfishplus-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.a(ServerboundMovePlayerPacket.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.a(ServerboundMovePlayerPacket.java) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at net.minecraft.util.thread.BlockableEventLoop.d(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.d(ReentrantBlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at net.minecraft.util.thread.BlockableEventLoop.x(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at net.minecraft.util.thread.BlockableEventLoop.c(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.20.4.jar:git-PufferfishPlus-46]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

---

**Additional server information**

**BanFromClaim version:** 1.7.4
**Server version (use /ver):** Paper 1.20.4
**Plugin list:** GriefPreventation, BanFromClaim

**Comment by Baktus79** [comment]
I will fix this in the next update :)

**Comment by Baktus79** [comment]
The new release is out and the issue should be fixed.
